// <auto-generated />
using System;
using Daily.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Daily.Data.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Daily.Data.Entities.Daily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("LinesOfCode");

                    b.Property<string>("NotDone");

                    b.Property<string>("Problems");

                    b.Property<string>("Today")
                        .IsRequired();

                    b.Property<Guid>("UserId");

                    b.Property<string>("Yesterday")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Dailies");
                });
#pragma warning restore 612, 618
        }
    }
}
